version: "3.8"

## Different image versions were built for the following test cases
# Web:
# version 0.1 -> 10 Tomcat thread limit + no fixed delay added to requests
# version 0.2 -> 10 Tomcat thread limit + 300ms fixed delay added to requests
# version 0.3 -> no thread limit + 300ms fixed delay added to requests

# WebFlux:
# version 0.1 -> no fixed delay added to requests
# version 0.2 -> 300ms fixed delay added to requests

services:
  # this is a jvm image, available after running "bootBuildImage" gradle task
  web-jvm:
    container_name: web-jvm-virtual-threads
    image: luismcunha/spring-web-redis-jvm-virtual-threads:0.1
    environment:
      PORT: 8080
      KEY_PREFIX: 'WEB:JVM:VIRTUAL:'
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '4'
    networks:
      - spring-redis-network
    depends_on:
      - redis-db
  # this is a graalvm native image, available after running "bootBuildImage" gradle task
  web-native:
    container_name: web-native-virtual-threads
    image: luismcunha/spring-web-redis-native-virtual-threads:0.1
    environment:
      KEY_PREFIX: 'WEB:NATIVE:VIRTUAL:'
      PORT: 8081
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          cpus: '4'
    ports:
      - "8081:8081"
    networks:
      - spring-redis-network
    depends_on:
      - redis-db

  # this is a jvm image, available after running "bootBuildImage" gradle task
  web-jvm-os-threads:
    container_name: web-jvm-os-threads
    image: luismcunha/spring-web-redis-jvm-os-threads:0.1
    environment:
      KEY_PREFIX: 'WEB:JVM:OS:'
      PORT: 8082
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: '4'
    networks:
      - spring-redis-network
    depends_on:
      - redis-db
  # this is a native image, available after running "bootBuildImage" gradle task
  web-native-os-threads:
    container_name: web-native-os-threads
    image: luismcunha/spring-web-redis-native-os-threads:0.1
    environment:
      KEY_PREFIX: 'WEB:NATIVE:OS:'
      PORT: 8083
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '4'
    networks:
      - spring-redis-network
    depends_on:
      - redis-db
  # this is a jvm image, available after running "bootBuildImage" gradle task
  webflux-jvm:
    container_name: webflux-jvm
    image: luismcunha/spring-webflux-redis-jvm:0.1
    environment:
      KEY_PREFIX: 'WEBFLUX:JVM:'
      PORT: 8084
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          cpus: '4'
    networks:
      - spring-redis-network
    depends_on:
      - redis-db
  # this is a graalvm native image, available after running "bootBuildImage" gradle task
  webflux-native:
    container_name: webflux-native
    image: luismcunha/spring-webflux-redis-native:0.1
    environment:
      KEY_PREFIX: 'WEBFLUX:NATIVE:'
      PORT: 8085
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          cpus: '4'
    networks:
      - spring-redis-network
    depends_on:
      - redis-db
  redis-db:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"
    networks:
      - spring-redis-network
networks:
  spring-redis-network:
